CREATE PROCEDURE dbo.sp_GetUsers
AS
BEGIN
	SET NOCOUNT ON;
	BEGIN TRY
		SELECT *
		FROM dbo.Userlogin;
	END TRY
	BEGIN CATCH
		DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
		RAISERROR(@ErrorMessage, 16, 1);
	END CATCH
END;
GO